# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_sampling <- function(K, num_samples, probs) {
    .Call('_bnplasso_int_sampling', PACKAGE = 'bnplasso', K, num_samples, probs)
}

sample_beta_conj_sigma <- function(X, tX, tXX, y, tau2, sigma2, mu) {
    .Call('_bnplasso_sample_beta_conj_sigma', PACKAGE = 'bnplasso', X, tX, tXX, y, tau2, sigma2, mu)
}

sample_beta_conj_sigma_float <- function(X, tX, tXX, y, tau2, sigma2, mu) {
    .Call('_bnplasso_sample_beta_conj_sigma_float', PACKAGE = 'bnplasso', X, tX, tXX, y, tau2, sigma2, mu)
}

sample_beta_ind_sigma <- function(X, tX, tXX, y, tau2, sigma2, mu) {
    .Call('_bnplasso_sample_beta_ind_sigma', PACKAGE = 'bnplasso', X, tX, tXX, y, tau2, sigma2, mu)
}

sample_beta_ind_sigma_float <- function(X, tX, tXX, y, tau2, sigma2, mu) {
    .Call('_bnplasso_sample_beta_ind_sigma_float', PACKAGE = 'bnplasso', X, tX, tXX, y, tau2, sigma2, mu)
}

step2_blockedGibbs_dbl <- function(tau2, lambda2_all, omega, K) {
    .Call('_bnplasso_step2_blockedGibbs_dbl', PACKAGE = 'bnplasso', tau2, lambda2_all, omega, K)
}

step2_blockedGibbs_flt <- function(tau2, lambda2_all, omega, K) {
    .Call('_bnplasso_step2_blockedGibbs_flt', PACKAGE = 'bnplasso', tau2, lambda2_all, omega, K)
}

NumVec_to_EigenVec <- function(x) {
    .Call('_bnplasso_NumVec_to_EigenVec', PACKAGE = 'bnplasso', x)
}

NumVec_to_EigenVec_float <- function(x) {
    .Call('_bnplasso_NumVec_to_EigenVec_float', PACKAGE = 'bnplasso', x)
}

EigenVec_to_NumVec <- function(x) {
    .Call('_bnplasso_EigenVec_to_NumVec', PACKAGE = 'bnplasso', x)
}

EigenVecFloat_to_NumVec <- function(x) {
    .Call('_bnplasso_EigenVecFloat_to_NumVec', PACKAGE = 'bnplasso', x)
}

get_tXX <- function(X) {
    .Call('_bnplasso_get_tXX', PACKAGE = 'bnplasso', X)
}

